name: install go

on:
  push:
    branches:
      - main

jobs:
  install-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uese: actions/setup-go@v5
      - run: go version